apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fko5syijm-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fko5syijm-go 
  name: fko5syijm-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fko5syijm-go 
